openapi: 3.0.0
info:
  title: Zones
  version: '1.0'
servers:
  - url: 'https://devfsm.westus.cloudapp.azure.com/FsmREST/api/1'
paths:
  '/auth/zones/{zoneID}':
    parameters:
      - type: string
        name: zoneID
        in: path
        required: true
    put:
      summary: ''
      responses:
        '200':
          description: OK
      description: prueba
  auth/zones:
    parameters: []
    post:
      summary: Ws create zone
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: |-
          {
            name:string,
            countryId:integer,
            stateSrovidenceRegionId:integer,
            cityId:integer,
            communeId:integer,
            tds: {
              tenantId:integer,
              domiainId:integer,
              subdomainId:integer
            }
          }
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: ''
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
